USE JIHAD;

CREATE TABLE STUDENT (
    ROLL CHAR(4) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(60) UNIQUE,
    ADDRESS VARCHAR(255),
    AGE INT CHECK (AGE>=18)
);

CREATE TABLE LIBRARY (
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    BOOKNAME VARCHAR(50),
    WHOHIRED_ROLL CHAR(4),

    FOREIGN KEY (WHOHIRED_ROLL) REFERENCES STUDENT(ROLL)
    -- CONSTRAINT FK_WHOHIRED_ROLL FOREIGN KEY (WHOHIRED_ROLL) REFERENCES STUDENT (ROLL)
);
