-- Creating the DEPARTMENTS table
CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL
);

-- Creating the EMPLOYEES table with a foreign key to the DEPARTMENTS table
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALARY DECIMAL(10, 2),
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

-- Insert data into DEPARTMENTS table
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(10, 'ACCOUNTING'),
(20, 'MARKETING'),
(30, 'IT'),
(40, 'HR');

-- Insert data into EMPLOYEES table
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID) VALUES
(101, 'John', 'Doe', 3000.00, 10),
(102, 'Jane', 'Smith', 2500.00, 20),
(103, 'Peter', 'Parker', 2600.00, 20),
(104, 'Bruce', 'Wayne', 1500.00, 30),
(105, 'Clark', 'Kent', 2800.00, 30),
(106, 'Diana', 'Prince', 3200.00, 20),
(107, 'Steve', 'Rogers', 2200.00, 30),
(108, 'Natasha', 'Romanoff', 4000.00, 10),
(109, 'Tony', 'Stark', 5000.00, 40),
(110, 'Bruce', 'Banner', 2000.00, 20);

-- ami peter er id diye oor salary janbo then peter er salary theke kom jader salary tader record dekhbo
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 144;

SELECT * FROM EMPLOYEES WHERE SALARY < 2500;

-- SAME JINISH TA SUBQUERY DIYE KORLE EMON HOBE:
SELECT * FROM EMPLOYEES WHERE SALARY < (
	SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 144
    );


-- JE HIGHEST SALARY PAY TAR RECORD DEKHBO
SELECT * FROM EMPLOYEES WHERE SALARY = (
										SELECT MAX(SALARY) FROM EMPLOYEES
										);


-- duita table ase department(d.id, d.name) and employee(d.id and all the details of employees of that department).
-- amake department name dibe then oi department er all employee er details show kora lagbe.

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = (
	SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'MARKETING'
);

SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = (
	SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'MARKETING'
);

-- IT DEPARTMENT E KOYJON KAJ KORE BER KORBO
SELECT COUNT(*) AS MEMEBERS FROM EMPLOYEES WHERE DEPARTMENT_ID = (
	SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'IT'
);